//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NormalizacionDirecciones
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DireccionEntities : DbContext
    {
        public DireccionEntities()
            : base("name=DireccionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<EMB_DIRECCIONES> EMB_DIRECCIONES { get; set; }
        public DbSet<EMB_HOMOLOGACION_BARRIO> EMB_HOMOLOGACION_BARRIO { get; set; }
    }
}
