//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NormalizacionDirecciones
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMB_DIRECCIONES
    {
        public decimal idDireccion { get; set; }
        public string RMTCON { get; set; }
        public string RMTRCCB { get; set; }
        public string nivsocio { get; set; }
        public string dirAlterna { get; set; }
        public string zonapostal { get; set; }
        public string coddane { get; set; }
        public string coddireccion { get; set; }
        public string fuente { get; set; }
        public string validacionPlaca { get; set; }
        public string longitude { get; set; }
        public string barrioTraducido { get; set; }
        public string latitude { get; set; }
        public string dirtrad { get; set; }
        public string coddirplaca { get; set; }
        public string localidad { get; set; }
        public string validacion { get; set; }
        public string estado { get; set; }
        public string barrio { get; set; }
        public string esambigua { get; set; }
        public string zona { get; set; }
        public string dirIngresada { get; set; }
        public string ciudadIngresada { get; set; }
        public Nullable<System.DateTime> fechaConsulta { get; set; }
    }
}
