//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NormalizacionDirecciones
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMB_HOMOLOGACION_BARRIO
    {
        public decimal idHomologacion { get; set; }
        public string barrioServicio { get; set; }
        public string barrioEmermedica { get; set; }
        public string ciudad { get; set; }
    }
}
