//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NormalizacionDirecciones
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMB_NORMALIZA_DIRECCIONES_LOG
    {
        public decimal idLogDirecciones { get; set; }
        public string idAplicacion { get; set; }
        public string idErrorLog { get; set; }
        public string descripcionError { get; set; }
        public Nullable<System.DateTime> fechaHora { get; set; }
        public string usuarioLog { get; set; }
    }
}
