USE [PROCESOS]
GO

/****** OBJECT:  TABLE [DBO].[EMB_USUARIOTURNOS]    SCRIPT DATE: 26/02/2016  ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [DBO].[EMA_USUARIO](
	[USUARIOID] [INT] IDENTITY(1,1) NOT NULL,
	[USUARIO] [NVARCHAR](64) NOT NULL,
	[TIPODOCUMENTO] [NVARCHAR](16) NOT NULL,
	[DOCUMENTO] [NVARCHAR](50) NOT NULL,
	[NOMBREUSUARIO] [NVARCHAR](512) NOT NULL,
	[CORREO] [NVARCHAR](128) NOT NULL,
	[ACTIVO] [BIT] NOT NULL,
	[FECHAULTIMASESION] [DATETIME] NULL,
	[FECHAREGISTRO] [DATETIME] NOT NULL CONSTRAINT [DF_EMA_USUARIO_FECHAREGISTRO]  DEFAULT (GETDATE()),
	[FECHAMODIFICACION] [DATETIME] NULL,
	[USUARIOCREACION] [NVARCHAR](50) NULL,
	[USUARIOMODIFICACION] [NVARCHAR](50) NULL,
 CONSTRAINT [PK_EMA_USUARIO] PRIMARY KEY CLUSTERED 
(
	[USUARIOID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


