USE [PROCESOS]
GO

/****** OBJECT:  TABLE [DBO].[EMA_ROLXMENU]    SCRIPT DATE: 26/02/2016 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [DBO].[EMA_ROLXMENU](
	[ROLXMENUID] [INT] IDENTITY(1,1) NOT NULL,
	[ROLID] [INT] NOT NULL,
	[MENUID] [INT] NOT NULL,
 CONSTRAINT [PK_EMA_ROLXMENU] PRIMARY KEY CLUSTERED 
(
	[ROLXMENUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [DBO].[EMA_ROLXMENU]  WITH CHECK ADD  CONSTRAINT [FK_EMA_ROLXMENU_EMA_MENU] FOREIGN KEY([MENUID])
REFERENCES [DBO].[EMA_MENU] ([MENUID])
GO

ALTER TABLE [DBO].[EMA_ROLXMENU] CHECK CONSTRAINT [FK_EMA_ROLXMENU_EMA_MENU]
GO

ALTER TABLE [DBO].[EMA_ROLXMENU]  WITH CHECK ADD  CONSTRAINT [FK_EMA_ROLXMENU_EMA_ROLE] FOREIGN KEY([ROLID])
REFERENCES [DBO].[EMA_ROL] ([ROLID])
GO

ALTER TABLE [DBO].[EMA_ROLXMENU] CHECK CONSTRAINT [FK_EMA_ROLXMENU_EMA_ROLE]
GO


