USE [PROCESOS]
GO

/****** OBJECT:  TABLE [DBO].[EMA_MENU]    SCRIPT DATE: 26/02/2016 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [DBO].[EMA_MENU](
	[MENUID] [INT] IDENTITY(1,1) NOT NULL,
	[DESCRIPCION] [NVARCHAR](64) NOT NULL,
	[NODOPADREID] [INT] NULL,
	[CONTROLLER] [NVARCHAR](64) NULL,
	[ACTION] [NVARCHAR](64) NULL,
	[URL] [NVARCHAR](128) NULL,
	[FECHACREACION] [DATETIME] NOT NULL CONSTRAINT [DF_EMA_MENU_FECHACREACION]  DEFAULT (GETDATE()),
	[FECHAMODIFICACION] [DATE] NULL,
	[USUARIOCREACION] [NVARCHAR](50) NULL,
	[USUARIOMODIFICACION] [NVARCHAR](50) NULL,
 CONSTRAINT [PK_EMA_MENU] PRIMARY KEY CLUSTERED 
(
	[MENUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [DBO].[EMA_MENU]  WITH CHECK ADD  CONSTRAINT [FK_EMA_MENU_EMA_MENU] FOREIGN KEY([NODOPADREID])
REFERENCES [DBO].[EMA_MENU] ([MENUID])
GO

ALTER TABLE [DBO].[EMA_MENU] CHECK CONSTRAINT [FK_EMA_MENU_EMA_MENU]
GO


